<!-- Js Plugins -->
<script src="{{ asset('website/js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('website/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('website/js/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('website/js/jquery.nicescroll.min.js') }}"></script>
<script src="{{ asset('website/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('website/js/jquery.countdown.min.js') }}"></script>
<script src="{{ asset('website/js/jquery.slicknav.js') }}"></script>
<script src="{{ asset('website/js/mixitup.min.js') }}"></script>
<script src="{{ asset('website/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('website/js/main.js') }}"></script>